name: .NET Core (deb)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Build with dotnet
      run: |
        sudo apt install libkrb5-dev -y
        dotnet tool install --global dotnet-deb
        dotnet deb install
        dotnet restore
        dotnet build wdhan.csproj /t:CreateDeb -r linux-x64 -c Release
        mv ./bin/Release/netcoreapp3.1/linux-x64/wdhan.*.deb ./bin/Release/netcoreapp3.1/linux-x64/wdhan.deb
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wdhan.deb
        path: ./bin/Release/netcoreapp3.1/linux-x64/wdhan.deb
