name: .NET Core (deb)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build with dotnet
      run: |
        dotnet tool install --global dotnet-deb
        dotnet deb install
        dotnet restore
        dotnet build pigmeat.csproj /t:CreateDeb --configuration Release
        mv ./bin/Release/netcoreapp3.1/pigmeat.*.deb ./bin/Release/netcoreapp3.1/pigmeat.deb
    - name: Upload artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: pigmeat.deb
        path: ./bin/Release/netcoreapp3.1/pigmeat.deb
