name: .NET Core (Linux)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Build with dotnet
      run: |
        sudo apt install libkrb5-dev -y
        dotnet publish -r linux-x64 -c Release
        chmod +x ./bin/Release/netcoreapp3.1/linux-x64/native/wdhan
        strip --strip-all ./bin/Release/netcoreapp3.1/linux-x64/native/wdhan
        tar -cvf wdhan.tar ./bin/Release/netcoreapp3.1/linux-x64/native/wdhan
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wdhan
        path: ./wdhan.tar
