name: .NET Core (rpm)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.3.100
    - name: Build with dotnet
      run: |
        dotnet tool install --global dotnet-rpm
        dotnet rpm install
        dotnet restore
        dotnet rpm --configuration Release --no-restore
        mv ./bin/Release/netcoreapp3.1/pigmeat.*.rpm ./bin/Release/netcoreapp3.1/pigmeat.rpm
    - name: Upload artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: pigmeat.rpm
        path: ./bin/Release/netcoreapp3.1/pigmeat.rpm
