name: Generate documentation
on:
  push:
    branches:
      - master # Default release branch

jobs:
  generate:
    name: Generate and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate
        run: |
          cd ./doxygen
          sudo apt install doxygen -y
          doxygen Doxyfile
          sh ./doxygraph.sh

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./doxygen/OUT/html/
          publish_branch: gh-pages  # deploying branch
          user_name: Doxygen
          user_email: em@emsa.cf
          commit_message: "Updating documentation"