name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for introducing your first issue in the WDHAN repository. Your feedback is much appreciated, and will be reviewed soon.'
        pr-message: 'Thank you for your first pull request in the WDHAN repository. Your contributions are much appreciated, and will be reviewed soon.'
