name: Publish to Snapcraft

on: [push]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.snapcraft_token }}
        use_lxd: true
    - name: Build snap
      run: |
        sudo snapcraft --use-lxd
        snapcraft push --release edge *.snap